python evaluation\match.py -n collins result\collins_0.00_0.00.txt 
python evaluation\match.py -n collins result\collins_0.00_0.05.txt 
python evaluation\match.py -n collins result\collins_0.00_0.10.txt 
python evaluation\match.py -n collins result\collins_0.00_0.15.txt 
python evaluation\match.py -n collins result\collins_0.00_0.20.txt 
python evaluation\match.py -n collins result\collins_0.00_0.25.txt 
python evaluation\match.py -n collins result\collins_0.00_0.30.txt 
python evaluation\match.py -n collins result\collins_0.00_0.35.txt 
python evaluation\match.py -n collins result\collins_0.00_0.40.txt 
python evaluation\match.py -n collins result\collins_0.00_0.45.txt 
python evaluation\match.py -n collins result\collins_0.00_0.50.txt 
python evaluation\match.py -n collins result\collins_0.00_0.55.txt 
python evaluation\match.py -n collins result\collins_0.00_0.60.txt 
python evaluation\match.py -n collins result\collins_0.00_0.65.txt 
python evaluation\match.py -n collins result\collins_0.00_0.70.txt 
python evaluation\match.py -n collins result\collins_0.00_0.75.txt 
python evaluation\match.py -n collins result\collins_0.00_0.80.txt 
python evaluation\match.py -n collins result\collins_0.00_0.85.txt 
python evaluation\match.py -n collins result\collins_0.00_0.90.txt 
python evaluation\match.py -n collins result\collins_0.00_0.95.txt 
python evaluation\match.py -n collins result\collins_0.00_1.00.txt 
python evaluation\match.py -n collins result\collins_0.50_0.00.txt 
python evaluation\match.py -n collins result\collins_0.50_0.05.txt 
python evaluation\match.py -n collins result\collins_0.50_0.10.txt 
python evaluation\match.py -n collins result\collins_0.50_0.15.txt 
python evaluation\match.py -n collins result\collins_0.50_0.20.txt 
python evaluation\match.py -n collins result\collins_0.50_0.25.txt 
python evaluation\match.py -n collins result\collins_0.50_0.30.txt 
python evaluation\match.py -n collins result\collins_0.50_0.35.txt 
python evaluation\match.py -n collins result\collins_0.50_0.40.txt 
python evaluation\match.py -n collins result\collins_0.50_0.45.txt 
python evaluation\match.py -n collins result\collins_0.50_0.50.txt 
python evaluation\match.py -n collins result\collins_0.50_0.55.txt 
python evaluation\match.py -n collins result\collins_0.50_0.60.txt 
python evaluation\match.py -n collins result\collins_0.50_0.65.txt 
python evaluation\match.py -n collins result\collins_0.50_0.70.txt 
python evaluation\match.py -n collins result\collins_0.50_0.75.txt 
python evaluation\match.py -n collins result\collins_0.50_0.80.txt 
python evaluation\match.py -n collins result\collins_0.50_0.85.txt 
python evaluation\match.py -n collins result\collins_0.50_0.90.txt 
python evaluation\match.py -n collins result\collins_0.50_0.95.txt 
python evaluation\match.py -n collins result\collins_0.50_1.00.txt 
python evaluation\match.py -n collins result\collins_1.00_0.00.txt 
python evaluation\match.py -n collins result\collins_1.00_0.05.txt 
python evaluation\match.py -n collins result\collins_1.00_0.10.txt 
python evaluation\match.py -n collins result\collins_1.00_0.15.txt 
python evaluation\match.py -n collins result\collins_1.00_0.20.txt 
python evaluation\match.py -n collins result\collins_1.00_0.25.txt 
python evaluation\match.py -n collins result\collins_1.00_0.30.txt 
python evaluation\match.py -n collins result\collins_1.00_0.35.txt 
python evaluation\match.py -n collins result\collins_1.00_0.40.txt 
python evaluation\match.py -n collins result\collins_1.00_0.45.txt 
python evaluation\match.py -n collins result\collins_1.00_0.50.txt 
python evaluation\match.py -n collins result\collins_1.00_0.55.txt 
python evaluation\match.py -n collins result\collins_1.00_0.60.txt 
python evaluation\match.py -n collins result\collins_1.00_0.65.txt 
python evaluation\match.py -n collins result\collins_1.00_0.70.txt 
python evaluation\match.py -n collins result\collins_1.00_0.75.txt 
python evaluation\match.py -n collins result\collins_1.00_0.80.txt 
python evaluation\match.py -n collins result\collins_1.00_0.85.txt 
python evaluation\match.py -n collins result\collins_1.00_0.90.txt 
python evaluation\match.py -n collins result\collins_1.00_0.95.txt 
python evaluation\match.py -n collins result\collins_1.00_1.00.txt 
